# BUCKET - User
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-user-bucket
spec:
  title: User
  description: User of the forum
  icon: account_circle
  primary: nick
  readOnly: false
  history: false
  properties:
    nick:
      type: string
      title: nick
      description: Description of the nick input
      options:
        position: bottom
    mail:
      type: string
      title: mail
      description: Description of the mail input
      options:
        position: bottom
      pattern: .+@.+\..+
    birthday:
      type: date
      title: birthday
      description: Description of the birthday input
      options:
        position: bottom
    gender:
      type: string
      title: gender
      description: Description of the gender input
      options:
        position: bottom
      enum:
        - Male
        - Female
        - Other
    level:
      type: string
      title: level
      description: Description of the level input
      options:
        position: bottom
      enum:
        - rookie
        - experienced
        - master
    followings:
      type: relation
      title: followings
      description: Description of the followings input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: nick
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    followers:
      type: relation
      title: followers
      description: Description of the followers input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: nick
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    profile_picture:
      type: storage
      title: profile_picture
      description: Description of the profile_picture input
      options:
        position: bottom
    bio:
      type: textarea
      title: bio
      description: Description of the bio input
      options:
        position: bottom
    identity_id:
      type: string
      title: identity_id
      description: Description of the identity_id input
      options:
        position: bottom
  acl:
    write: auth._id == document.identity_id
    read: true == true
  order: 5
---
# BUCKET - Category
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-category-bucket
spec:
  title: Category
  description: Category of the Forum
  icon: category
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    titles:
      type: relation
      title: titles
      description: Description of the titles input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-title-bucket
    surveys:
      type: relation
      title: surveys
      description: Description of the surveys input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-survey-bucket
    popularity:
      type: number
      title: popularity
      description: Description of the popularity input
      options:
        position: bottom
      minimum: 0
      maximum: 100
  acl:
    write: true==true
    read: true==true
  order: 6
---
# BUCKET - Title
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-title-bucket
spec:
  title: Title
  description: Title of the forum
  icon: title
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    content:
      type: string
      title: content
      description: Description of the content
      options:
        position: bottom
    user:
      type: relation
      title: user
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    comments:
      type: relation
      title: comments
      description: Description of the comments input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-comment-bucket
    created_at:
      type: date
      title: date
      description: Description of the date input
      options:
        position: bottom
      default: created_at
  acl:
    write: auth._id == document.owner_user.identity_id
    read: true==true
  order: 7
---
# BUCKET - Comment
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-comment-bucket
spec:
  title: Comment
  description: Comment of the Forum
  icon: question_answer
  primary: content
  readOnly: false
  history: false
  properties:
    content:
      type: string
      title: content
      description: Description of the content input
      options:
        position: bottom
    date:
      type: date
      title: date
      description: Description of the date input
      options:
        position: bottom
      default: :created_at
    user:
      type: relation
      title: user
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: nick
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    likes:
      type: relation
      title: likes
      description: Description of the likes input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: nick
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    dislikes:
      type: relation
      title: dislikes
      description: Description of the dislikes input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: nick
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    images:
      type: array
      title: images
      description: Description of the images input
      options:
        position: bottom
      items:
        title: Title of the items
        type: storage
    comments:
      type: relation
      title: comments
      description: Description of the comments input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: nick
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-comment-bucket
  acl:
    write: auth._id == document.user.identity_id
    read: true==true
  order: 8
---
# BUCKET - Survey
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-forum-asset-survey-bucket
spec:
  title: Survey
  description: Survey of the forum
  icon: quiz
  primary: title
  readOnly: false
  history: false
  properties:
    user:
      type: relation
      title: user
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-forum-asset-user-bucket
    title:
      type: string
      title: title
      description: Description of the title input
      options:
        position: bottom
    selections:
      type: array
      title: options
      items:
        type: object
        properties:
          option:
            type: string
            title: Name
          total_votes:
            type: number
            title: Votes
            minimum: 0
        title: selections
      options:
        position: bottom
  acl:
    write: auth._id == document.user.identity_id
    read: true==true
  order: 9